name: fireworks_counter
description: Modified Flutter counter template app with fireworks.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fireworks:
    path: ../fireworks

flutter:
  uses-material-design: true
